apiVersion: v1
kind: Pod
metadata:
  name: dnspod
  labels:
    app: dnspod
spec:
  containers:
    - name: dnspod
      image: naison/gost:latest
      imagePullPolicy: IfNotPresent
      command:
        - gost -D
      resources:
        requests:
          memory: "256Mi"
          cpu: "128m"
        limits:
          memory: "512Mi"
          cpu: "256m"
      ports:
        - containerPort: 22
  restartPolicy: Always
  priorityClassName: system-cluster-critical
