name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Minikube
      timeout-minutes: 30
      uses: medyagh/setup-minikube@master

    - name: Sleep 180 seconds waiting for minikube ready
      run: sleep 180

    - name: Kubernetes info
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
        cat ~/.kube/config
        ls -lah ~/.kube/config
    - name: Install demo bookinfo
      run: kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml

    - name: Build
      run: make kubevpn-linux

    - name: Test
      run: go test -v ./...
