name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup Minikube
        timeout-minutes: 30
        uses: medyagh/setup-minikube@master

      - name: Kubernetes info
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system -o wide
      - name: Install demo bookinfo
        run: kubectl apply -f https://raw.githubusercontent.com/wencaiwulue/kubevpn/master/samples/bookinfo.yaml

      - name: Build
        run: make kubevpn-linux

      - name: Wait for pods reviews to be ready
        run: |
          kubectl wait pods -l app=reviews --for=condition=Ready --timeout=600s
          kubectl get all -o wide

      - name: Test
        run: go test -v ./test/
