name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Minikube
      timeout-minutes: 30
      uses: medyagh/setup-minikube@master

    - name: Kubernetes info
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system -o wide
        cat ~/.kube/config
        ls -lah ~/.kube/config
    - name: Install demo bookinfo
      run: kubectl apply -l version!=v2,version!=v3 -f https://raw.githubusercontent.com/istio/istio/release-1.12/samples/bookinfo/platform/kube/bookinfo.yaml

    - name: Build
      run: make kubevpn-linux

    - name: Wait for pods reviews to be ready
      run: kubectl wait pods -l app=reviews --for=condition=Ready --timeout=600s

    - name: Test
      run: go test -v ./test/
